name = "sensorgrid-ingest"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
DASHBOARD_ORIGIN = "https://sensorgrid.site"
NEON_AUTH_BASE_URL = "https://ep-dawn-forest-adg30i2s.neonauth.c-2.us-east-1.aws.neon.tech/neondb/auth"
